/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

sourceSets {
    main {
        kotlin {
            srcDirs("src")
        }
    }
}