/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":icsparser"))
    implementation(files("libs/json-simple-1.1.1.jar"))
    implementation(project(":AuthCat"))
}

application {
    // Define the main class for the application.
    mainClass = "net.nathcat.calendar.MainKt"
}
